### ISSUE TITLE
Error There is no package called 'DBI', laxy loading failed for package monkey learn

### ISSUE THREAD

**Issue by bkesha** [ropenscilabs/monkeylearn#11]
Please review this error.

Error in loadNamespace(i, c(lib.loc, .libPaths()), versionCheck = vI[[i]]) : 
  there is no package called 'DBI'
ERROR: lazy loading failed for package 'monkeylearn'
* removing 'C:/Users/keshavPC/Documents/R/win-library/3.3/monkeylearn'
Error: Command failed (1)

**Comment by masalmon** [comment]
@bkesha do you get this error on loading the package (`library("monkeylearn")`) or when trying to install it?

**Comment by masalmon** [comment]
And does `library(dplyr)` work?

**Comment by masalmon** [comment]
@bkesha now that `dplyr` is only suggested, can you install the package? `dplyr` is still needed for one vignette but you can use the package without it.

**Comment by masalmon** [comment]
@bkesha now you can also try installing the package from CRAN via `install.packages("monkeylearn")`. Please re-open if you have the problem again.
